Repository incognitochain/incognito-chain, pull requests merged in 2019-10, with the labels that each got.

#300 - need to check nil pointer exception before using it -> fix bug cras…
  server.go
Labels: bug, critical, high

#298 Open source all of our specs
  .gitignore
  specs/ethereum_bridge.md
Labels: high

#320 update new readme with more info on how to read the code
  .gitignore
  README.md
  specs/architecture.md
Labels: enhancement

#323 Implement New Method To Select Node into Pending Validator List
  blockchain/beaconprocess.go
  blockchain/beaconproducer.go
  blockchain/beaconutils.go
  blockchain/beaconutils_test.go
  blockchain/constants.go
Labels: enhancement

#352 fix issue #351
  consensus/engine.go
Labels: high

#354 Fix eth bridge missing producer
  blockchain/bridge_test.go
  blockchain/shardproducer.go
  go.mod
  go.sum
  mocks/DatabaseInterface.go
Labels: bug

#365 Dev/issue339
  blockchain/beaconutils.go
  blockchain/bridge_test.go
  blockchain/constants.go
  blockchain/shardprocess.go
  blockchain/shardproducer.go
  common/hash.go
  incognitokey/keygenfortest/2s-256node/beaconprivate.json
  incognitokey/keygenfortest/2s-256node/beaconprivateseed.json
  incognitokey/keygenfortest/2s-256node/beaconseed.json
  incognitokey/keygenfortest/2s-256node/keylist.json
  incognitokey/keygenfortest/2s-256node/shardprivate.json
  incognitokey/keygenfortest/2s-256node/shardprivateseed.json
  incognitokey/keygenfortest/2s-256node/shardseed.json
  incognitokey/keygenfortest/64s-100node/beaconprivate.json
  incognitokey/keygenfortest/64s-100node/beaconprivateseed.json
  incognitokey/keygenfortest/64s-100node/beaconseed.json
  incognitokey/keygenfortest/64s-100node/keylist.json
  incognitokey/keygenfortest/64s-100node/shardprivate.json
  incognitokey/keygenfortest/64s-100node/shardprivateseed.json
  incognitokey/keygenfortest/64s-100node/shardseed.json
  incognitokey/keygenfortest/main.go
  keylist.json
  keylist_256.json
  rpcserver/websocket.go
  rpcserver/ws_beststate.go
  run_node.sh
  utility/generate-txs/main.go
  utility/genkeypairprivacy.go
  utility/genminingkey.go
Labels: enhancement

#370 Update ABI of ETH bridge's smart contract
  common/constants.go
  go.mod
  go.sum
Labels: enhancement
