Repository incognitochain/incognito-chain, pull requests merged in 2019-12, with the labels that each got.

#540 Hot fix
  blockchain/synker.go
Labels: Priority: Critical, Type: Bug

#537 Highway remove masternode
  .tmuxinator.yml
  keylist.json
  mempool/shardtobeaconpool.go
  peerv2/blockrequester.go
  peerv2/connmanager.go
  peerv2/highway.pb.go
  run_new.sh
  server.go
Labels: Priority: High, Type: Enhancement

#541 Highway fix bug synker
  .tmuxinator.yml
  blockchain/synker.go
  keylist.json
  mempool/shardtobeaconpool.go
  peerv2/blockrequester.go
  peerv2/connmanager.go
  peerv2/highway.pb.go
  run_new.sh
  server.go
Labels: Priority: High, Type: Bug

#550 Add rpc to get highway's multiaddr
  peerv2/connmanager.go
  peerv2/connmanager_test.go
  peerv2/param.go
Labels: Priority: High, Type: Enhancement

#552 Pdex min liquidity for new pair
  blockchain/beaconpdeproducer.go
  common/constants.go
  metadata/metadata.go
Labels: Type: Enhancement

#558 Support get block shard and beacon by hashes
  netsync/getblock.go
  peerv2/blockprovider.go
  peerv2/blockrequester.go
  peerv2/connmanager.go
  server.go
Labels: Type: Enhancement

#563 Highway fix sync s2b
  blockchain/synker.go
  connmanager/connmanager.go
  consensus/engine.go
  metrics/monitor.go
  peerv2/host.go
  server.go
Labels: Priority: High, Type: Bug

#572 Remove 10k prv min requirement constraints for adding liquidity to pdex
  blockchain/beaconpdeproducer.go
  common/constants.go
  metadata/metadata.go
Labels: Type: Enhancement

#580 Support sync shard block by hash
  blockchain/messages.go
  blockchain/synker.go
  netsync/getblock.go
  peerv2/blockprovider.go
  peerv2/blockrequester.go
  server.go
Labels: Priority: High, Type: Enhancement

#581 Increase MaxCallRecvMsgSize to 50 MBs per request
  peerv2/blockrequester.go
  peerv2/constants.go
Labels: Priority: High, Type: Bug

#585 fix revert bug
  blockchain/revert.go
Labels: Priority: Critical, Type: Bug

#599 - hotfix revert when forking, only reomve token when it is not bridge…
  blockchain/revert.go
Labels: Priority: High, Type: Bug

#604 Move highway.pb.go to package proto
  peerv2/blockprovider.go
  peerv2/blockrequester.go
  peerv2/connmanager.go
  peerv2/proto/highway.pb.go
Labels: Priority: Low, Type: Feature

#612 temp fix for issue #576
  blockchain/shardbeststate.go
  blockchain/synker.go
Labels: Priority: High

#613 temp fix issue #611
  blockchain/beaconprocess.go
  blockchain/messages.go
  blockchain/shardprocess.go
  blockchain/synker.go
Labels: Priority: High

#621 Update pde adding liquidity formula
  blockchain/beaconpdeprocess.go
  blockchain/beaconpdeproducer.go
  blockchain/pdetxsbuilder.go
  blockchain/shardproducer.go
  common/constants.go
  database/interface.go
  database/lvdb/pde.go
  metadata/pdecontribution.go
  metadata/pdecontributionresponse.go
  metadata/pdetraderesponse.go
  rpcserver/constants.go
  rpcserver/http_pde.go
  rpcserver/rpcinterface.go
  rpcserver/rpcservice/databaseservice.go
Labels: Type: Enhancement

#630 [highway] Update synker and add unittest
  blockchain/messages.go
  blockchain/syncblockutils.go
  blockchain/syncblockutils_test.go
  blockchain/synker.go
  mocks/DatabaseInterface.go
  netsync/netsync.go
Labels: Priority: Medium, Type: Enhancement

#652 Fix bug not closing BlockRequester connection
  peerv2/blockrequester.go
  peerv2/constants.go
Labels: Priority: Critical, Type: Bug

#609 [highway] Unittest for flow incognito node registers to highway
  blockchain/beaconprocess.go
  go.mod
  peerv2/connmanager.go
  peerv2/connmanager_test.go
  peerv2/dispatch.go
  peerv2/mocks/ConsensusData.go
  peerv2/mocks/Host.go
  peerv2/mocks/Network.go
  peerv2/mocks/Registerer.go
  peerv2/mocks/Subscriber.go
  peerv2/submanager.go
  peerv2/submanager_test.go
  run_new.sh
  server.go
Labels: Priority: Medium, Type: Enhancement

#666 Remove Custom Token
  blockchain/blockchain.go
  blockchain/hashutils.go
  blockchain/interface.go
  blockchain/revert.go
  blockchain/shardblock.go
  blockchain/shardbody.go
  blockchain/shardcrossprocess.go
  blockchain/shardprocess.go
  blockchain/shardproducer.go
  blockchain/shardutils.go
  blockchain/txviewpoint.go
  common/constants.go
  database/interface.go
  mempool/mempool.go
  mempool/mempoolpersistence.go
  mempool/mempoolshardtxs.go
  metadata/metadata.go
  netsync/netsync.go
  peer/peer.go
  peer/peerconn.go
  peerv2/dispatch.go
  rpcserver/http_block.go
  rpcserver/http_estimatefee.go
  rpcserver/http_testing.go
  rpcserver/http_tx.go
  rpcserver/http_utils.go
  rpcserver/http_wallet.go
  rpcserver/jsonresult/gettransactiondetailresult.go
  rpcserver/jsonresult/listcustomtokenresult.go
  rpcserver/jsonresult/listunspentcustomtoken.go
  rpcserver/rpcinterface.go
  rpcserver/rpcservice/blockservice.go
  rpcserver/rpcservice/commonservice.go
  rpcserver/rpcservice/txservice.go
  rpcserver/ws_account.go
  server.go
  tests/it_crossshard_transaction_test.go
  tests/it_transaction_test.go
  tests/testcase.json
  tests/testsdata/transaction/cross_custom_token_privacy_transaction.json
  tests/testsdata/transaction/cross_custom_token_transaction.json
  tests/testsdata/transaction/cross_normal_transaction.json
  tests/testsdata/transaction/custom_token_privacy_transaction.json
  tests/testsdata/transaction/custom_token_transaction.json
  tests/testsdata/transaction/normal_transaction.json
  transaction/common.go
  transaction/constants.go
  transaction/txnormaltoken.go
  transaction/txnormaltoken_test.go
  transaction/txnormaltokendata.go
  transaction/txnormaltokendata_test.go
  transaction/txprivacy.go
  wire/message.go
  wire/messagetransactiontoken.go
Labels: Priority: Critical, Type: Maintenance

#644 [Highway] Choose randomly one highway and maintain connection
  go.mod
  go.sum
  peerv2/blockrequester.go
  peerv2/connmanager.go
  peerv2/constants.go
  peerv2/param.go
  peerv2/proto/highway.pb.go
  peerv2/rpcclient.go
  peerv2/submanager.go
Labels: Priority: High, Type: Feature

#667 Create portal v2 spec
  specs/portalv2.md
Labels: Type: Documentation
