Repository incognitochain/incognito-chain, pull requests merged in 2019-11, with the labels that each got.

#466 Order keys in stateful map of pdex in order to avoid hash verificatio…
  blockchain/beaconstatefulinsts.go
Labels: bug, critical

#467 fix bug add info when creating tx
  wasm/gomobile/param.go
Labels: bug

#469 Fix remove liquidity issue for pdex
  blockchain/beaconpdeproducer.go
Labels: Type: Bug

#470 Fix the sanity validation issue for pdex withdrawal request
  metadata/pdewithdrawalrequest.go
Labels: Priority: Medium, Type: Bug

#477 Deduplicate removing liquidity txs
  blockchain/pdetxsbuilder.go
  metadata/pdewithdrawalresponse.go
Labels: Type: Bug

#480 - add more info into RPC
  rpcserver/http_wallet.go
  rpcserver/jsonresult/listcustomtokenresult.go
Labels: Priority: Medium, Type: Feature

#489 fix bug tx no output, has only fee
  privacy/zeroknowledge/paymentwitness.go
Labels: Priority: Critical

#494 Highway: redo pr #483 without fixed block producer - 2nd attempt
  .tmuxinator.yml
  blockchain/beaconbeststate.go
  blockchain/beaconprocess.go
  blockchain/beaconproducer.go
  blockchain/blockchain.go
  blockchain/interface.go
  blockchain/messages.go
  blockchain/shardbeststate.go
  blockchain/syncblockutils.go
  blockchain/synker.go
  config.go
  consensus/engine.go
  go.mod
  go.sum
  incognitokey/highwaycommittee.go
  keylist.json
  mempool/beaconpool.go
  mempool/shardtobeaconpool.go
  netsync/getblock.go
  netsync/netsync.go
  peerv2/blockprovider.go
  peerv2/blockrequester.go
  peerv2/config.go
  peerv2/connmanager.go
  peerv2/dispatch.go
  peerv2/highway.pb.go
  peerv2/host.go
  peerv2/utils.go
  server.go
  wire/messagepeerstate.go
Labels: Priority: High, Type: Feature

#499 APIs for pdex analytics
  rpcserver/constants.go
  rpcserver/http_pde.go
  rpcserver/rpcinterface.go
Labels: Type: Enhancement

#502 Add more log for debugging S2B issue
  blockchain/messages.go
  mempool/shardtobeaconpool.go
Labels: Priority: High

#506 Highway fix register
  peerv2/blockrequester.go
  peerv2/connmanager.go
  server.go
Labels: Priority: High, Type: Bug

#507 Highway: retry forced-register if it's failed
  peerv2/blockrequester.go
  peerv2/connmanager.go
Labels: Priority: High, Type: Bug

#509 Fix sync s2b blocks
  mempool/shardtobeaconpool.go
Labels: Priority: High, Type: Bug

#517 Fix convert price api issue
  rpcserver/http_pde.go
Labels: Type: Bug

#520 Peerv2 use common.Logger
  log.go
  peerv2/blockprovider.go
  peerv2/blockrequester.go
  peerv2/connmanager.go
  peerv2/dispatch.go
  peerv2/host.go
  peerv2/log.go
  peerv2/utils.go
Labels: Priority: Low, Type: Enhancement

#521 Peerv2 use common.Logger
  log.go
  peerv2/blockprovider.go
  peerv2/blockrequester.go
  peerv2/connmanager.go
  peerv2/dispatch.go
  peerv2/host.go
  peerv2/log.go
  peerv2/utils.go
Labels: Priority: Low, Type: Enhancement

#526 ETH light node monitoring
  bin/bridge/eth-lightnode-monitoring.py
Labels: Type: Maintenance

#528 Fix bug txcustomtoken not published
  blockchain/params.go
  peerv2/connmanager.go
  server.go
Labels: Priority: High, Type: Bug

#531 Hot fix panic ws and only let committee members publish peerstate
  blockchain/blockchain.go
  blockchain/synker.go
  rpcserver/ws_account.go
  server.go
Labels: Priority: High, Type: Bug
