Repository incognitochain/incognito-chain, pull requests merged in 2020-01, with the labels that each got.

#672 Unittest for peerv2's connmanager
  peerv2/blockrequester.go
  peerv2/blockrequester_test.go
  peerv2/connmanager.go
  peerv2/connmanager_test.go
  peerv2/mocks/GRPCDialer.go
  peerv2/mocks/HighwayDiscoverer.go
  peerv2/mocks/Registerer.go
  peerv2/rpcclient/param.go
  peerv2/rpcclient/rpcclient.go
Labels: Priority: Medium, Type: Enhancement

#679 Portalv2 spec
  specs/portalv2.md
Labels: Type: Documentation

#681 Portalv2 spec
  specs/portal.md
  specs/portalv2.md
Labels: Type: Documentation

#686 Remove blockchain.Synker.Status.Lock in OnPeerStateReceived
  blockchain/messages.go
Labels: Priority: Critical, Type: Bug

#690 Update portal.md
  specs/portal.md
Labels: Type: Documentation

#693 Increase request timeout to 20s
  peerv2/constants.go
Labels: Priority: High, Type: Bug

#706 Hotfix crossshard pool
  blockchain/beaconprocess.go
  blockchain/interface.go
  blockchain/shardcrossprocess.go
  blockchain/shardproducer.go
  blockchain/synker.go
  mempool/crossshardpool.go
Labels: Priority: Critical, Type: Bug

#707 Fix bug FindBeaconHeightForCrossShardBlock
  blockchain/beaconprocess.go
  blockchain/interface.go
  blockchain/shardcrossprocess.go
  blockchain/shardproducer.go
  blockchain/synker.go
  mempool/crossshardpool.go
Labels: Priority: Critical, Type: Bug

#721 Update portal spec
  specs/portal.md
Labels: Type: Documentation

#723 Update portal spec
  specs/portal.md
Labels: Type: Documentation
