Repository incognitochain/incognito-chain, pull requests merged in 2020-03, with the labels that each got.

#789 Incognito mode
  blockchain/beaconbridgeprocess.go
  blockchain/beaconbridgeproducer.go
  blockchain/bridge.go
  metadata/burningrequest.go
  metadata/common.go
  metadata/constants.go
  rpcserver/constants.go
  rpcserver/http_bridge.go
  rpcserver/http_burn.go
  rpcserver/rpcinterface.go
  rpcserver/rpcservice/commonservice.go
Labels: Type: Feature

#797 hotfix: mempool
  mempool/mempool.go
Labels: Type: Bug

#804 Fix potential issues of eth-bridge
  metadata/constants.go
  metadata/issuingethrequest.go
Labels: Type: Enhancement

#817 hotfix: fix object type
  dataaccessobject/statedb/accessor_burn.go
  dataaccessobject/statedb/statedb.go
Labels: Type: Bug

#821 shardprocess: revert beststate on failure
  blockchain/shardprocess.go
Labels: Type: Enhancement

#823 hot fix reward
  blockchain/beaconprocess.go
  blockchain/salary.go
  database/lvdb/epochreward.go
  database/lvdb/epochreward_test.go
  database/lvdb/prevstate.go
Labels: Priority: Critical, Type: Bug

#824 reward: add debug rpc
  rpcserver/constants.go
  rpcserver/http_testing.go
  rpcserver/rpcinterface.go
Labels: Type: Enhancement

#825 reward: add debug rpc
  rpcserver/constants.go
  rpcserver/http_testing.go
  rpcserver/rpcinterface.go
Labels: Type: Enhancement
